# Generated by Django 2.2.19 on 2022-09-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_posts',
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
